function test_thermobaroMin4epma()
%TEST_THERMOBAROMIN4EPMA Regression test for thermobaroMin4EPMA outputs.
%
% This test runs the following calculation:
%
%   Calculation mode : Thermometer: pressure range
%   Input file       : expected_output_Results_NaN2zero.xlsx
%   Mineral group    : Pyroxene
%   Thermometer      : Brey and_Kohler 1990 (Opx Ca)
%   Pressure unit    : kbar
%   Minimum pressure : 10 kbar
%   Maximum pressure : 30 kbar
%   Selected data    : test_003
%
% How to run:
%   1) Place the input workbook in the same directory as this test file:
%          expected_output_Results_NaN2zero.xlsx
%
%   2) Place the expected output files in:
%          test/expected
%
%   3) Run this function and follow the dialog instructions displayed in
%      the Command Window.
%
% Expected output files:
%   expected_output_Results_NaN2zero_ ...
%       Geotherm_rangeP_Pyroxene_BreyKohler1990Ca_P10to30kbar.xlsx
%
%   expected_output_Results_NaN2zero_ ...
%       Geotherm_rangeP_Pyroxene_BreyKohler1990Ca_ ...
%       P10to30kbar_TPplot.png
%

%% 0) Initialize the test environment
% Close existing figures so that previously opened plots do not interfere
% with the thermobaroMin4EPMA calculation or the generated P-T plot.
close all;

disp('==================================================================');
disp(' test_thermobaroMin4epma');
disp(' Regression test for thermobaroMin4EPMA');
disp('==================================================================');

%% Resolve the test and expected-output directories
% Determine the location of this test file. This allows the test to work
% even when MATLAB was started from another current directory.
thisFile = mfilename("fullpath");
testDir  = fileparts(thisFile);
expDir   = fullfile(testDir, "expected");

% Check that the expected-output directory exists before starting the test.
if ~isfolder(expDir)
    error( ...
        'test_thermobaroMin4epma:ExpectedDirectoryNotFound', ...
        'Expected-output directory was not found:\n%s', ...
        expDir);
end

% Run thermobaroMin4EPMA from the test directory so that the file-selection
% dialog opens near the test data and generated files can be located
% consistently.
originalDir = pwd;
cleanupDir = onCleanup(@() cd(originalDir));
cd(testDir);

%% 1) Define the input and output file names
% The input workbook is the Results workbook generated by the
% cationCalc4EPMA test, with all NaN values replaced by zero.
inputName = ...
    "expected_output_Results_NaN2zero.xlsx";

% thermobaroMin4EPMA should generate one Excel workbook containing the
% calculated temperatures and one PNG file containing the P-T plot.
outputExcelName = ...
    "expected_output_Results_NaN2zero_" + ...
    "Geotherm_rangeP_Pyroxene_" + ...
    "BreyKohler1990Ca_P10to30kbar.xlsx";

outputPngName = ...
    "expected_output_Results_NaN2zero_" + ...
    "Geotherm_rangeP_Pyroxene_" + ...
    "BreyKohler1990Ca_P10to30kbar_TPplot.png";

% The generated files are expected in the test directory.
inputPath       = fullfile(testDir, inputName);
outputExcelPath = fullfile(testDir, outputExcelName);
outputPngPath   = fullfile(testDir, outputPngName);

% Reference files used for regression comparison are stored separately in
% the expected directory.
expectedExcelPath = fullfile(expDir, outputExcelName);
expectedPngPath   = fullfile(expDir, outputPngName);

%% 2) Confirm that all required test files are available
disp('------------------------------------------------------------------');
disp('Step 01: Checking test files');

% Confirm that the input workbook exists and can be opened before launching
% the interactive thermobaroMin4EPMA workflow.
if ~isfile(inputPath)
    error( ...
        'test_thermobaroMin4epma:InputFileNotFound', ...
        'Input workbook was not found:\n%s', ...
        inputPath);
end

% Reading the sheet names confirms that the workbook is accessible and is
% recognized as a valid spreadsheet by MATLAB.
inputSheets = sheetnames(inputPath);

if isempty(inputSheets)
    error( ...
        'test_thermobaroMin4epma:InvalidInputWorkbook', ...
        'No worksheets were found in the input workbook:\n%s', ...
        inputPath);
end

% Confirm that the reference Excel workbook exists.
if ~isfile(expectedExcelPath)
    error( ...
        'test_thermobaroMin4epma:ExpectedExcelNotFound', ...
        'Expected Excel output was not found:\n%s', ...
        expectedExcelPath);
end

% Confirm that the reference P-T plot exists.
if ~isfile(expectedPngPath)
    error( ...
        'test_thermobaroMin4epma:ExpectedPngNotFound', ...
        'Expected PNG output was not found:\n%s', ...
        expectedPngPath);
end

fprintf('  Input workbook: %s\n', inputName);
fprintf('  Number of input worksheets: %d\n', numel(inputSheets));
fprintf('  Expected Excel file found.\n');
fprintf('  Expected PNG file found.\n');

%% 3) Remove output files left by a previous test
disp('------------------------------------------------------------------');
disp('Step 02: Removing previous test outputs');

% Old output files could cause a false-positive result if the current
% calculation is canceled or fails before writing new files. Therefore,
% delete any existing generated outputs before launching the program.
deleteFileIfPresent(outputExcelPath);
deleteFileIfPresent(outputPngPath);

%% 4) Run thermobaroMin4EPMA
disp('------------------------------------------------------------------');
disp('Step 03: Running thermobaroMin4EPMA');
disp(' ');
disp('Select the following options in the dialogs:');
disp(' ');
disp('  1. Calculation mode');
disp('       Thermometer: pressure range');
disp(' ');
disp('  2. Input data file');
disp('       expected_output_Results_NaN2zero.xlsx');
disp(' ');
disp('  3. Mineral group');
disp('       Pyroxene');
disp(' ');
disp('  4. Thermometer');
disp('       Brey and_Kohler 1990 (Opx Ca)');
disp(' ');
disp('  5. Pressure unit');
disp('       kbar');
disp(' ');
disp('  6. Minimum pressure');
disp('       10');
disp(' ');
disp('  7. Maximum pressure');
disp('       30');
disp(' ');
disp('  8. Data');
disp('       test_003');
disp(' ');
disp('------------------------------------------------------------------');

% Launch the main thermobarometry program. The selections listed above must
% be entered manually so that the complete GUI workflow is also tested.
thermobaroMin4EPMA();

% Close calculation figures after the output files have been exported.
close all;

%% 5) Confirm that the expected output files were generated
disp('------------------------------------------------------------------');
disp('Step 04: Checking generated output files');

if ~isfile(outputExcelPath)
    error( ...
        'test_thermobaroMin4epma:ExcelOutputNotGenerated', ...
        ['The expected Excel output was not generated.\n' ...
         'Expected file:\n%s'], ...
        outputExcelPath);
end

if ~isfile(outputPngPath)
    error( ...
        'test_thermobaroMin4epma:PngOutputNotGenerated', ...
        ['The expected P-T plot was not generated.\n' ...
         'Expected file:\n%s'], ...
        outputPngPath);
end

fprintf('  Generated Excel file: %s\n', outputExcelName);
fprintf('  Generated PNG file:   %s\n', outputPngName);

%% 6) Compare the generated Excel workbook with the expected workbook
disp('------------------------------------------------------------------');
disp('Step 05: Comparing Excel output');

% Compare the worksheet names first. This detects missing, additional, or
% reordered worksheets before individual worksheet contents are examined.
compareExcelWorkbooks(outputExcelPath, expectedExcelPath);

disp('  Excel workbook is consistent with the expected output.');

%% 7) Compare the generated P-T plot with the expected PNG
disp('------------------------------------------------------------------');
disp('Step 06: Comparing P-T plot');

% Compare decoded image data rather than the raw PNG file bytes. This avoids
% differences caused only by PNG compression or non-image metadata.
comparePngImages(outputPngPath, expectedPngPath);

disp('  P-T plot is consistent with the expected output.');

%% 8) Report successful completion
disp('==================================================================');
disp('All thermobaroMin4EPMA outputs are consistent with expected files!');
disp('==================================================================');

end


function deleteFileIfPresent(filePath)
%DELETEFILEIFPRESENT Delete a previous output file when it exists.
%
% Removing old outputs ensures that the regression test evaluates files
% generated during the current run rather than files from an earlier run.

if isfile(filePath)
    delete(filePath);
    fprintf('  Deleted previous output: %s\n', filePath);
else
    fprintf('  No previous output found: %s\n', filePath);
end

end


function compareExcelWorkbooks(outputPath, expectedPath)
%COMPAREEXCELWORKBOOKS Compare all worksheets in two Excel workbooks.
%
% Worksheet names, table dimensions, variable names, variable classes, and
% table values are compared. NaN values are treated as equal by isequaln.

outputSheets   = sheetnames(outputPath);
expectedSheets = sheetnames(expectedPath);

% Confirm that both workbooks contain the same worksheets in the same order.
if ~isequal(outputSheets, expectedSheets)
    error( ...
        'test_thermobaroMin4epma:SheetNamesDoNotMatch', ...
        ['Test failed: worksheet names do not match.\n\n' ...
         'Generated workbook:\n%s\n\nExpected workbook:\n%s'], ...
        strjoin(outputSheets, newline), ...
        strjoin(expectedSheets, newline));
end

% Read and compare each worksheet independently so that an error message can
% identify the worksheet containing the mismatch.
for i = 1:numel(expectedSheets)
    sheetName = expectedSheets(i);

    fprintf('  Comparing worksheet: %s\n', sheetName);

    outputTable = readtable( ...
        outputPath, ...
        'Sheet', sheetName, ...
        'VariableNamingRule', 'preserve');

    expectedTable = readtable( ...
        expectedPath, ...
        'Sheet', sheetName, ...
        'VariableNamingRule', 'preserve');

    % Compare table dimensions before comparing the full table.
    if height(outputTable) ~= height(expectedTable) || ...
            width(outputTable) ~= width(expectedTable)

        error( ...
            'test_thermobaroMin4epma:TableSizeDoesNotMatch', ...
            ['Test failed: table size does not match in worksheet "%s".\n' ...
             'Generated size: %d rows x %d columns\n' ...
             'Expected size:  %d rows x %d columns'], ...
            sheetName, ...
            height(outputTable), width(outputTable), ...
            height(expectedTable), width(expectedTable));
    end

    % Compare the variable names explicitly to distinguish structural
    % differences from differences in the calculated values.
    if ~isequal( ...
            outputTable.Properties.VariableNames, ...
            expectedTable.Properties.VariableNames)

        error( ...
            'test_thermobaroMin4epma:VariableNamesDoNotMatch', ...
            ['Test failed: column names do not match in worksheet "%s".\n' ...
             'Generated workbook:\n%s\n\nExpected workbook:\n%s'], ...
            sheetName, ...
            strjoin( ...
                string(outputTable.Properties.VariableNames), newline), ...
            strjoin( ...
                string(expectedTable.Properties.VariableNames), newline));
    end

    % Compare the classes of corresponding table variables. A change from
    % numeric to text, for example, should be detected even if displayed
    % values appear similar in Excel.
    for columnNumber = 1:width(expectedTable)
        outputClass = class(outputTable{:, columnNumber});
        expectedClass = class(expectedTable{:, columnNumber});

        if ~strcmp(outputClass, expectedClass)
            variableName = expectedTable.Properties.VariableNames{columnNumber};

            error( ...
                'test_thermobaroMin4epma:VariableClassDoesNotMatch', ...
                ['Test failed: data class does not match for variable "%s" ' ...
                 'in worksheet "%s".\n' ...
                 'Generated class: %s\n' ...
                 'Expected class:  %s'], ...
                variableName, sheetName, outputClass, expectedClass);
        end
    end

    % isequaln treats NaN values in corresponding positions as equal and
    % otherwise requires the table contents to match exactly.
    if ~isequaln(outputTable, expectedTable)
        mismatchDescription = findFirstTableMismatch( ...
            outputTable, expectedTable);

        error( ...
            'test_thermobaroMin4epma:ExcelValuesDoNotMatch', ...
            ['Test failed: values do not match in worksheet "%s".\n%s\n' ...
             'Generated workbook:\n%s'], ...
            sheetName, mismatchDescription, outputPath);
    end
end

end


function description = findFirstTableMismatch(outputTable, expectedTable)
%FINDFIRSTTABLEMISMATCH Identify the first mismatching table variable.
%
% This function provides a more informative error than a workbook-level
% comparison by reporting the first column containing different values.

description = "The first mismatching cell could not be identified.";

for columnNumber = 1:width(expectedTable)
    outputVariable = outputTable{:, columnNumber};
    expectedVariable = expectedTable{:, columnNumber};

    if isequaln(outputVariable, expectedVariable)
        continue
    end

    variableName = expectedTable.Properties.VariableNames{columnNumber};

    % Numeric and logical data can be compared element by element while
    % accounting for NaN values in corresponding positions.
    if isnumeric(outputVariable) || islogical(outputVariable)
        equalMask = ...
            (outputVariable == expectedVariable) | ...
            (isnan(outputVariable) & isnan(expectedVariable));

        mismatchLinearIndex = find(~equalMask, 1, 'first');

        if ~isempty(mismatchLinearIndex)
            [rowNumber, valueColumn] = ind2sub( ...
                size(outputVariable), mismatchLinearIndex);

            outputValue = outputVariable(rowNumber, valueColumn);
            expectedValue = expectedVariable(rowNumber, valueColumn);

            description = sprintf( ...
                ['First detected mismatch:\n' ...
                 '  Table row:       %d\n' ...
                 '  Variable:        %s\n' ...
                 '  Element column:  %d\n' ...
                 '  Generated value: %s\n' ...
                 '  Expected value:  %s'], ...
                rowNumber, ...
                variableName, ...
                valueColumn, ...
                valueToText(outputValue), ...
                valueToText(expectedValue));

            return
        end
    end

    % For text, categorical, datetime, cell, or other data classes, report
    % the first variable containing a difference.
    description = sprintf( ...
        ['A mismatch was detected in variable "%s".\n' ...
         'Generated class: %s\n' ...
         'Expected class:  %s'], ...
        variableName, class(outputVariable), class(expectedVariable));

    return
end

end


function text = valueToText(value)
%VALUETOTEXT Convert a scalar table value into diagnostic text.

if isnumeric(value) || islogical(value)
    text = mat2str(value, 16);
elseif isstring(value)
    text = char(value);
elseif ischar(value)
    text = value;
else
    text = char(string(value));
end

end


function comparePngImages(outputPath, expectedPath)
%COMPAREPNGIMAGES Compare the decoded contents of two PNG files.
%
% Image pixels, indexed-image color maps, and alpha channels are compared
% independently. PNG metadata and file compression are not compared.

[outputImage, outputMap, outputAlpha] = imread(outputPath);
[expectedImage, expectedMap, expectedAlpha] = imread(expectedPath);

% Compare the dimensions of the decoded image arrays.
if ~isequal(size(outputImage), size(expectedImage))
    error( ...
        'test_thermobaroMin4epma:PngSizeDoesNotMatch', ...
        ['Test failed: PNG image dimensions do not match.\n' ...
         'Generated size: %s\n' ...
         'Expected size:  %s\n' ...
         'Generated image:\n%s'], ...
        mat2str(size(outputImage)), ...
        mat2str(size(expectedImage)), ...
        outputPath);
end

% Compare the image color or indexed-pixel data.
if ~isequal(outputImage, expectedImage)
    mismatchIndex = find(outputImage ~= expectedImage, 1, 'first');

    [rowNumber, columnNumber, channelNumber] = ind2sub( ...
        size(outputImage), mismatchIndex);

    error( ...
        'test_thermobaroMin4epma:PngPixelsDoNotMatch', ...
        ['Test failed: PNG pixel data do not match.\n' ...
         'First detected mismatch:\n' ...
         '  Row:               %d\n' ...
         '  Column:            %d\n' ...
         '  Channel:           %d\n' ...
         '  Generated value:   %g\n' ...
         '  Expected value:    %g\n' ...
         'Generated image:\n%s'], ...
        rowNumber, ...
        columnNumber, ...
        channelNumber, ...
        double(outputImage(mismatchIndex)), ...
        double(expectedImage(mismatchIndex)), ...
        outputPath);
end

% Indexed PNG files may use a separate color map. Confirm that the map also
% matches so identical indices cannot refer to different displayed colors.
if ~isequaln(outputMap, expectedMap)
    error( ...
        'test_thermobaroMin4epma:PngColorMapDoesNotMatch', ...
        ['Test failed: PNG color maps do not match.\n' ...
         'Generated image:\n%s'], ...
        outputPath);
end

% Compare transparency information when an alpha channel is present.
if ~isequal(outputAlpha, expectedAlpha)
    error( ...
        'test_thermobaroMin4epma:PngAlphaDoesNotMatch', ...
        ['Test failed: PNG alpha channels do not match.\n' ...
         'Generated image:\n%s'], ...
        outputPath);
end

end